openapi: 3.0.0
servers:
  - url: 'https://api.jamma.cn/wechat'
  - url: 'http://gateway.l.jamma.cn/wechat'
  - url: 'http://api.l.jamma.cn/wechat'
  - url: 'http://localhost:3000/wechat'
info:
  version: 2.0.1
  title: wechat
  description: 微信公众号系统API
paths:
  /oauth/uri:
    get:
      description: 生成公众号验证uri
      parameters:
        - in: query
          name: uri
          description: 目标uri
          schema:
            type: string
        - in: query
          name: state
          description: 开发者可提供的数据
          schema:
            type: string
        - in: query
          name: scope
          description: 作用范围，值为snsapi_userinfo和snsapi_base，前者用于弹出，后者用于跳转
          schema:
            type: string
        - in: query
          name: web
          description: 是否用于网站授权
          schema:
            type: integer
      responses:
        '200':
          description: 返回验证uri
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Uri'
  /oauth/{code}:
    get:
      description: 查询对应 openid 和 unionid
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 查询结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthInfo'
  /oauth/{code}/user:
    get:
      description: 查询对应的用户信息
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 查询结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
  /users/{openid}:
    get:
      description: 查询对应 openid 的用户信息
      parameters:
        - name: openid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 查询结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
  /qrcodes:
    post:
      description: 生成二维码
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateQrcodeInfo'            
      responses:
        '200':
          description: 结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QrcodeInfo'
  /qrcodes/{ticket}:
    get:
      description: 获取二维码图片网址
      parameters:
        - name: ticket
          in: path
          required: true
          schema:
            type: string          
      responses:
        '200':
          description: 结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Uri'
components:
  schemas:
    AuthInfo:
      type: object
      properties:
        openid:
          type: string
          example: 'root'
        unionid:
          type: string
          example: '123'
      description: 注册信息
    UserInfo:
      type: object
      properties:
        openid:
          type: string
          example: '596d5cb3baeeaf00203de4ec'
          description: 用户的唯一标识
        unionid:
          type: string
          example: '3a90dd3a53914eae857793297738574a85ae74e5914fce723b9dc82d562a31cf'
          description: 只有在用户将公众号绑定到微信开放平台帐号后，才会出现该字段。
        nickname:
          type: string
          example: 'jeff'
          description: 用户昵称
        sex:
          type: integer
          format: int32
          description: 用户的性别，值为1时是男性，值为2时是女性，值为0时是未知
        province:
          type: string
          description: 用户个人资料填写的省份
        city:
          type: string
          description: 普通用户个人资料填写的城市
        country:
          type: string
          example: 'jeff'
          description: 国家，如中国为CN
        headimgurl:
          type: string
          description: 用户头像，最后一个数值代表正方形头像大小（有0、46、64、96、132数值可选，0代表640*640正方形头像），用户没有头像时该项为空。若用户更换头像，原有头像URL将失效。
        privilege:
          type: object
          description: 用户特权信息，json 数组，如微信沃卡用户为（chinaunicom）
      description: 用户信息
    Uri:
      type: object
      properties:
        uri:
          type: string
          example: 'http://www.baidu.com'
      description: 验证uri信息
    CreateQrcodeInfo:
      type: object
      description: 二维码信息
      properties:
        expire:
          type: integer
          format: int32
          description: 该二维码有效时间，以秒为单位。 最大不超过2592000（即30天），此字段如果不填，则默认有效期为30秒。
        limit:
          type: integer
          format: int32
          description: 二维码类型，默认0表示临时二维码
        scene:
          type: integer
          format: int32
          description: 场景值ID，临时二维码时为32位非0整型，永久二维码时最大值为100000（目前参数只支持1--100000）, 如果是字符串类型，长度限制为1到64
    QrcodeInfo:
      type: object
      description: 二维码信息
      properties:
        ticket:
          type: string
          example: '596d5cb3baeeaf00203de4ec'
          description: 获取的二维码ticket，凭借此ticket可以在有效时间内换取二维码。
        expire:
          type: integer
          format: int32
          description: 该二维码有效时间，以秒为单位。 最大不超过2592000（即30天）。
        url:
          type: string
          example: 'http://www.baidu.com'
          description: 二维码图片解析后的地址，开发者可根据该地址自行生成需要的二维码图片
